spring.application.name=infrastructure
spring.mvc.static-path-pattern=/webapp/**
spring.datasource.url=jdbc:postgresql://localhost:5432/staged
spring.datasource.username=postgres
spring.datasource.password=insanity25
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA settings
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

spring.security.user.name=liz
spring.security.user.password=hiawatha
server.error.whitelabel.enabled=false

spring.mvc.static-path-pattern=/static/**